lang: zh-cn

translations:
  zh-cn:
    ui:
      CATEGORY: '分类：'
    category:
      1: '普通'
      2: '稀有'
      3: '史诗'
      4: '传说'
    enchantments:
      Rage:
        name: '怒火'
        description:
          - '右键进入 {duration} 秒狂暴模式'
          - '对敌人造成 {damage_multiplier} 倍伤害的同时对自己造成 {self_damage} 点伤害'
          - '冷却时间: {cooldown} 秒'
          - '可用于附魔剑'

enchantments:
  Rage:
    max-level: 5
    levels:
      1:
        category: 1
        parameters:
          duration: 20
          damage_multiplier: 1.2
          self_damage: 1
          cooldown: 40
      2:
        category: 2
        parameters:
          duration: 30
          damage_multiplier: 1.5
          self_damage: 1
          cooldown: 30
      3:
        category: 2
        parameters:
          duration: 30
          damage_multiplier: 1.8
          self_damage: 1
          cooldown: 25
      4:
        category: 3
        parameters:
          duration: 45
          damage_multiplier: 2
          self_damage: 0.5
          cooldown: 20
      5:
        category: 4
        parameters:
          duration: 60
          damage_multiplier: 3
          self_damage: 0.5
          cooldown: 15